import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';
import fs from 'node:fs';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

// Custom plugin to copy manifest.json and styles.css to build/ directory
const copyFilesPlugin = {
	name: 'copy-files',
	setup(build) {
		build.onEnd(() => {
			if (!fs.existsSync('build')) {
				fs.mkdirSync('build');
			}
			try {
				fs.copyFileSync('manifest.json', 'build/manifest.json');
				if (fs.existsSync('styles.css')) {
					fs.copyFileSync('styles.css', 'build/styles.css');
				}
				console.log('Required files successfully copied to build/ directory.');
			} catch (err) {
				console.error('Error copying build files:', err);
			}
		});
	}
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'build/main.js',
	minify: prod,
	plugins: [copyFilesPlugin],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
