name: Release Plugin

on:
  push:
    # Trigger the workflow only when version tags are pushed (e.g. 1.0.2 or v1.0.2)
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Build plugin
        run: npm run build

      - name: Create Release and Upload Assets
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "build/main.js,build/manifest.json,build/styles.css"
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
          tag: ${{ github.ref_name }}
          name: v${{ github.ref_name }}
          draft: false
          prerelease: false
